#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
apt-get -y update
apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;" /etc/nginx/sites-enabled/default
service nginx start
