#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy
echo -e "frontend myfront\n\tmode http\n\tbind *:80\n\tdefault_backend myback" >> /etc/haproxy/haproxy.cfg
echo -e "backend myback\n\tmode http\n\tbalance roundrobin\n\tserver 402357-web-01 35.153.50.54:80\n\tserver 402357-web-02 34.207.64.213:80" >> /etc/haproxy/haproxy.cfg
echo -e "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
