#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy
echo -e "frontend firstbalance\n\tmode http\n\tbind *:80\n\tdefault_backend web_servers" >> /etc/haproxy/haproxy.cfg
echo -e "backend web_servers\n\tmode http\n\tbalance roundrobin\n\tserver s1 34.204.82.8:80\n\tserver s2 3.86.13.94:80" >> /etc/haproxy/haproxy.cfg
echo -e "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
