#!/usr/bin/env bash
# Write a Bash script that configures a server to the above requirements
rm -rf /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
