#!/usr/bin/env bash
# Display Best School 10 times using until loop
call=1
while [ $call -le 10 ];
do
    if [ $call -eq 9 ];
then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi

    ((call++))
done
